# Generated by Django 5.2.1 on 2025-06-05 16:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MVPUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(help_text='CPF do usuário (formato: 000.000.000-00)', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato: 000.000.000-00', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, help_text='Telefone de contato (opcional)', max_length=20, verbose_name='Telefone')),
                ('ativo', models.BooleanField(default=True, help_text='Usuário ativo no sistema MVP', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(help_text='Usuário base do Django', on_delete=django.db.models.deletion.CASCADE, related_name='mvp_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Django')),
            ],
            options={
                'verbose_name': 'Usuário MVP',
                'verbose_name_plural': 'Usuários MVP',
                'db_table': 'mvp_user',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cpf'], name='mvp_user_cpf_13ec0d_idx'), models.Index(fields=['ativo', 'created_at'], name='mvp_user_ativo_aa6ae5_idx')],
            },
        ),
    ]
