# Generated by Django 5.2.1 on 2025-06-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mvpuser',
            name='cpf',
            field=models.CharField(help_text='CPF do usuário (será formatado automaticamente)', max_length=14, unique=True, verbose_name='CPF'),
        ),
    ]
